on:
  push:
    branches:
      - main

jobs:
  get_files:
    name: run_on_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Retrieve previous commit hash
        id: get_previous_commit
        run: |
          echo "::set-output name=commit::$(git log -1 --skip=1 --pretty=format:'%H')"

      - name: List modified files
        run: |
          files=$(git diff --name-only ${{ steps.get_previous_commit.outputs.commit }}..${{ github.sha }})
          echo "::set-output name=files::$files"
      
      - name: Check modified files for "abc/"
        run: |
          files=${{ steps.list_files.outputs.files }}
          for file in $files; do
            if [[ $file == "abc/"* ]]; then
              echo "abc"
              break
            fi
          done

      - name: Check modified files for "zzz/"
        run: |
          files=${{ steps.list_files.outputs.files }}
          for file in $files; do
            if [[ $file == "zzz/"* ]]; then
              echo "zzz"
              break
            fi
          done

      

