on:
  push:
    branches:
      - main

jobs:
  get_files:
    name: run_on_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Retrieve previous commit hash
        id: get_previous_commit
        run: |
          echo "::set-output name=commit::$(git log -1 --skip=1 --pretty=format:'%H')"

      - name: List modified files
        run: |
          IFS=$'\n' files=($(git diff --name-only ${{ steps.get_previous_commit.outputs.commit }}..${{ github.sha }}))
          for file in "${files[@]}"; do
            echo "$file"
          done >> $GITHUB_ENV

      - name: echo
        run: |
          echo ${{ env.GITHUB_ENV }}
            
