on:
  push:
    branches:
      - main

jobs:
  get_files:
    name: run_on_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Retrieve previous commit hash
        id: get_previous_commit
        run: |
          echo "::set-output name=commit::$(git log -1 --skip=1 --pretty=format:'%H')"

      - name: List modified files
        id: list_files
        run: |
          files=$(git diff --name-only ${{ steps.get_previous_commit.outputs.commit }}..${{ github.sha }})
          echo "::set-output name=files::$files"

      - name: Check modified files for "abc/"
        run: |
          for file in $files; do
            if [[ ${file} == "abc/"* ]]; then
              echo "abc"
              break
            else
              echo $file
            fi
          done
        shell: bash
      

