on:
  push:
    branches: [ main ]


jobs:
  get_files:
    name: run_on_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Modified files
        run: |
          git checkout -b new-branch
          git fetch origin main
          git diff --name-only origin/main