on:
  push:
    branches: [ main ]


jobs:
  get_files:
    name: run_on_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set Git user information
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Make changes
        run: |
          # Make your desired changes to the 'abc/def.txt' file
          echo "Example change" >> abc/def.txt

      - name: Stage changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Committing changes"

      - name: List modified files
        run: git diff --name-only HEAD~