on:
  push:
    branches: [ main ]


jobs:
  get_files:
    name: run_on_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Retrieve previous commit hash
        run: |
          PREVIOUS_COMMIT=$(git log -1 --skip=1 --pretty=format:"%H")

      - name: List modified files
        run: git diff --name-only $PREVIOUS_COMMIT..${{ github.sha }}